### ISSUE TITLE
errors during export of TangoTest

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/SimulatorDS#12]
Hi Sergi,
since I spend a few more hours on SimulatorDS, I paid more attention to warning and error messages so I noticed several strange behaviour.

In particular, exporting TangoTest, I got strange  output at the very end of export:

```
('sys/tg_test/1', 'no_value', 'unreadable!')
('sys/tg_test/1', 'throw_exception', 'unreadable!')
```

and I wondered why. However, the attributes are not specified:

```
$ ./gen_simulation.py export essai/TangoTest.txt essai/TangoTest.pck

Executing the generic simulation script ...
--------------------------------------------------------------------------------
export_attributes from:(['essai/TangoTest.txt'], 'essai/TangoTest.pck')
essai/TangoTest.txt
/home/gauron/SimulatorDS/essai/TangoTest.txt
devices to export: ['sys/tg_test/1']
sys/tg_test/1 (1/1)
('sys/tg_test/1', 'no_value', 'unreadable!')
('sys/tg_test/1', 'throw_exception', 'unreadable!')

essai/TangoTest.pck has been generated, now copy it to your test environment [host] and execute:

	python gen_simulation.py load essai/TangoTest.pck [tango test_db host]



['export'] done
```

Do you have any idea if it is a warning without interest or if there is  something I should fix?

**Comment by PhilLAL** [comment]
I noticed that several attributes are absent:
-  uchar_spectrum[_ro]
- uchar-image[_ro]

**Comment by sergirubio** [comment]
In the case of no_value and throw_exception; these are special attributes as they are used in TangoTest to check for errors in clients. I think they are a very special case, but anyway I will improve the traces

In the case of uchar arrays; as this is a relatively not-used type I may have omitted it in the code; I'll do a check.

Sorry for the late answers, I was on sick leave for most of summer and I've got a huge pile of work to do after comeback.

**Comment by PhilLAL** [comment]
No problem, and thank you for taking time to explain this point. There two attributes are not necessary for me, I just wondered why this behaviour. :)

**Comment by sergirubio** [comment]
I close this issue; for the uchar array attributes problems I'll work on issue #15
