### ISSUE TITLE
display order of attributes in generated DS

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/SimulatorDS#13]
Hi Sergi,
trying to check generated TangoTest simulated DS, I noticed that attributes are displayed in a different order than in the original DS.

I wondered it there is a way to make attributes appear in the same order? 
It would make it easier to compare and debug simulated DS.

Regards.

**Comment by sergirubio** [comment]
... in which client does it occur? shouldn't it be always sorted by lowercase?

**Comment by PhilLAL** [comment]
This is in AtkPanel, it displays as shown in #10 ticket of dalifard. 
I will look into the doc to understand how this is possible.

**Comment by sergirubio** [comment]
So ... which do you think is the proper behaviour? Keep original order or sorted order?
The first option is incompatible with using dict() and pickle

**Comment by PhilLAL** [comment]
I did not find anything explaining why an ATKPanel could use a display order different from lowercase. 
I create an issue to understand [this](https://github.com/tango-controls/atk/issues/3) but waiting for this, I think this in not absolutely necessary. :)

**Comment by sergirubio** [comment]
Hi,
As we currently have no solution for this issue, I'll close the ticket
In case you have feedback from the ATK team, you can reopen it
Sergi
