### ISSUE TITLE
need the mocked DS to be launched to export 

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/SimulatorDS#16]
Hi Sergi,
while trying to export a DS, I noticed that le mocked DS probably needs to be launched before exporting the DS through SimulatorDS

If this is the case
```
# Then export all the devices configuration to a pickle file
```
could probably be written
```
# Then export all the devices configuration to a pickle file after launching the DS to export
```
Am I right?

Regards

**Comment by sergirubio** [comment]
Yes, you're right, thanks for finding it!

**Comment by sergirubio** [comment]
Hi, I solved the issue in master/develop branches
