### ISSUE TITLE
adding attributes in PCK exported files

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/SimulatorDS#6]
Hi Sergi, 
I would like to understand the syntax of files generated by the operation `gen_simulation.py export devices.txt xgui_attributes.pck`.

I would like at first creating device including additionnal new attributes.
Is there any way to do this?
In one sentence : what is the format of these PCK files?

Thank you.

**Comment by sergirubio** [comment]
Hi,

In fact, the process is quite dummy

devices.txt will contain a list of either attributes or devices that will
be parsed by the script. As when parsing source files, the script simply
searchs for strings that look like tango names, and then it searches if
they exist in the Tango database.

If the names are found, then it proceeds to execute DeviceProxy.info(),
get_device_property(), get_attribute_list() and get_attribute_info() to
obtain all the information regarding device, server, class, types of
attributes and its format.

I also try to collect other information like the current value, polling
periods and event configurations and I finally write everything into a
nested dictionary, where the main keys are the device names and then
attributes and properties. For the attributes I try to mimic the structs
that are used internally in the get_attribute_config/set_attribute_config
commands of PyTango.

The format of the .pck file is arbitrary, just depends of the pickle
library that comes with python. That library allows to import/export
python objects to/from files. I could have used .json files instead and
probably I'll switch to that format in the future.

I hope this matches more or less with your questions, but if you want to
specify devices to be loaded to tango databases I think that the .csv
format is much more clear and easy to use.

I refer to this format:


https://github.com/tango-controls/PANIC/blob/master/panic/test/testdevs.csv

If this looks better for what you need tomorrow I can provide you more
examples.

Sergi
